<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Toggle</name>
   <tag></tag>
   <elementGuidId>cc6c9328-0533-4674-b01b-0b3f8fbce707</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Toggle')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2fca93b3-9cde-48d8-8333-d77186e88bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-footer-item</value>
      <webElementGuid>93a0d71f-d900-496c-b2da-dee82393952d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/radio</value>
      <webElementGuid>40a3b2e1-107d-4f27-88ba-5329714e45b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Toggle</value>
      <webElementGuid>9234350c-5a5d-4c40-99f9-f8ed49009563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/app-root[1]/app-test-site[1]/section[@class=&quot;hero has-background-white-ter&quot;]/div[@class=&quot;hero-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;columns is-multiline is-mobile&quot;]/div[@class=&quot;column is-3-desktop is-6-tablet&quot;]/app-menu[1]/div[@class=&quot;card&quot;]/footer[@class=&quot;card-footer&quot;]/a[@class=&quot;card-footer-item&quot;]</value>
      <webElementGuid>db7946e8-fab9-4e67-9f60-bf3c50874ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Toggle')]</value>
      <webElementGuid>7de1fdf1-f406-40f9-9198-9ab28e060f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Interact with different types of radio &amp; check boxes'])[1]/following::a[1]</value>
      <webElementGuid>a0ec8267-f82e-471f-9768-a56d3fdee3c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inner HTML'])[1]/following::a[1]</value>
      <webElementGuid>3815f3ee-d622-4524-8c6d-7023cd42dc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Switch different types of tabs or windows'])[1]/preceding::a[1]</value>
      <webElementGuid>01ac3239-6829-49ac-84cc-ae058081d9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tabs'])[1]/preceding::a[1]</value>
      <webElementGuid>4b9512fe-27e3-4037-865b-c3ce7610bbef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Toggle']/parent::*</value>
      <webElementGuid>9ad7b7cd-4493-44b4-ab37-b7ea9d2b9a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/radio')]</value>
      <webElementGuid>109d3215-6997-4acf-b7b4-465052f034e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div/div/div/div[2]/app-menu/div/footer/a</value>
      <webElementGuid>929222f0-eeb6-4872-a0bf-41f9cedc61a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/radio' and (text() = 'Toggle' or . = 'Toggle')]</value>
      <webElementGuid>6a8cbe29-a5ef-4ca7-bf1e-1385fb5f3f76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
