<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your full Name_fullName</name>
   <tag></tag>
   <elementGuidId>b0301562-3f6f-4f37-b69b-b514f6727312</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fullName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fullName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6bbeb80-a9b4-47c9-9dd4-43fc0597fb15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fullName</value>
      <webElementGuid>fd03bfcf-f184-4348-8a8c-befd280a4d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc6d592f-3e3a-4504-ace1-2ebcec9671dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter first &amp; last name</value>
      <webElementGuid>cd5c99e3-8768-4420-a2cc-084f49738c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input is-focused</value>
      <webElementGuid>51726064-4af2-4f8e-822a-be99cb0549b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fullName&quot;)</value>
      <webElementGuid>bee3f1cd-7a7a-41c3-b9a1-d62faecca522</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fullName']</value>
      <webElementGuid>2a9a8bb1-60ec-4024-a84d-dac5bf066449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>893d8026-5c98-4604-ba92-c330f4339093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fullName' and @type = 'text' and @placeholder = 'Enter first &amp; last name']</value>
      <webElementGuid>1ee39a44-cfa6-4eeb-8fbe-0b9a73220789</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
